import type { Metadata } from 'next'
import '@/styles/master.min.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import CssBaseline from '@mui/material/CssBaseline'
import { ThemeProvider } from '@mui/material'
import theme from '@/core/utils/theme/theme'
import Provider from '@/components/Providers/Provider'
import { PropsWithChildren } from 'react'

/* metadata for each one  */
export const metadata: Metadata = {
    title: 'shop',
    description: 'Generated by create next app'
}

const RootLayout = ({ children }: PropsWithChildren) => {
    return (
        <html lang='en'>
            <body>
                <AppRouterCacheProvider>
                    <ThemeProvider theme={theme}>
                        <CssBaseline />

                        <Provider>{children}</Provider>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}

export default RootLayout
