import type { Metadata } from "next";
import "@/styles/master.min.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from "@mui/material";
import theme from "@/core/utils/theme/theme"


export const metadata: Metadata = {
  title: "shop",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}

          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
